package com.lcy.yikao.web.dataobject;

import java.util.Date;

public class BmUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_user.id
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_user.email
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_user.reg_time
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    private Date regTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_user.gender
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_user.birthday
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_user.pwd
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_user.salt
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_user.status
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_user.gmt_modified
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_user.gmt_created
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    private Date gmtCreated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_user.id
     *
     * @return the value of bm_user.id
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_user.id
     *
     * @param id the value for bm_user.id
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_user.email
     *
     * @return the value of bm_user.email
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_user.email
     *
     * @param email the value for bm_user.email
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_user.reg_time
     *
     * @return the value of bm_user.reg_time
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_user.reg_time
     *
     * @param regTime the value for bm_user.reg_time
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_user.gender
     *
     * @return the value of bm_user.gender
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_user.gender
     *
     * @param gender the value for bm_user.gender
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_user.birthday
     *
     * @return the value of bm_user.birthday
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_user.birthday
     *
     * @param birthday the value for bm_user.birthday
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_user.pwd
     *
     * @return the value of bm_user.pwd
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_user.pwd
     *
     * @param pwd the value for bm_user.pwd
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_user.salt
     *
     * @return the value of bm_user.salt
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_user.salt
     *
     * @param salt the value for bm_user.salt
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_user.status
     *
     * @return the value of bm_user.status
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_user.status
     *
     * @param status the value for bm_user.status
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_user.gmt_modified
     *
     * @return the value of bm_user.gmt_modified
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_user.gmt_modified
     *
     * @param gmtModified the value for bm_user.gmt_modified
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_user.gmt_created
     *
     * @return the value of bm_user.gmt_created
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_user.gmt_created
     *
     * @param gmtCreated the value for bm_user.gmt_created
     *
     * @mbg.generated Wed Jan 23 21:15:15 CST 2019
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }
}